/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as MaisCaemRouteImport } from './routes/mais-caem'
import { Route as PlacasRouteImport } from './routes/placas'
import { Route as PsicotecnicoRouteImport } from './routes/psicotecnico'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SimuladoRouteImport } from './routes/simulado'
import { Route as SimuladoDemoRouteImport } from './routes/simulado-demo'
import { Route as TurboRouteImport } from './routes/turbo'
import { Route as BibliotecaIdRouteImport } from './routes/biblioteca.$id'
import { Route as ApiPixCreateRouteImport } from './routes/api/pix/create'
import { Route as ApiPixStatusRouteImport } from './routes/api/pix/status'
import { Route as ApiPixWebhookRouteImport } from './routes/api/pix/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisCaemRoute = MaisCaemRouteImport.update({
  id: '/mais-caem',
  path: '/mais-caem',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacasRoute = PlacasRouteImport.update({
  id: '/placas',
  path: '/placas',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicotecnicoRoute = PsicotecnicoRouteImport.update({
  id: '/psicotecnico',
  path: '/psicotecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoRoute = SimuladoRouteImport.update({
  id: '/simulado',
  path: '/simulado',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoDemoRoute = SimuladoDemoRouteImport.update({
  id: '/simulado-demo',
  path: '/simulado-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const TurboRoute = TurboRouteImport.update({
  id: '/turbo',
  path: '/turbo',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIdRoute = BibliotecaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BibliotecaRoute,
} as any)
const ApiPixCreateRoute = ApiPixCreateRouteImport.update({
  id: '/api/pix/create',
  path: '/api/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixStatusRoute = ApiPixStatusRouteImport.update({
  id: '/api/pix/status',
  path: '/api/pix/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixWebhookRoute = ApiPixWebhookRouteImport.update({
  id: '/api/pix/webhook',
  path: '/api/pix/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/conquistas': typeof ConquistasRoute
  '/mais-caem': typeof MaisCaemRoute
  '/placas': typeof PlacasRoute
  '/psicotecnico': typeof PsicotecnicoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulado': typeof SimuladoRoute
  '/simulado-demo': typeof SimuladoDemoRoute
  '/turbo': typeof TurboRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
  '/api/pix/create': typeof ApiPixCreateRoute
  '/api/pix/status': typeof ApiPixStatusRoute
  '/api/pix/webhook': typeof ApiPixWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/conquistas': typeof ConquistasRoute
  '/mais-caem': typeof MaisCaemRoute
  '/placas': typeof PlacasRoute
  '/psicotecnico': typeof PsicotecnicoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulado': typeof SimuladoRoute
  '/simulado-demo': typeof SimuladoDemoRoute
  '/turbo': typeof TurboRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
  '/api/pix/create': typeof ApiPixCreateRoute
  '/api/pix/status': typeof ApiPixStatusRoute
  '/api/pix/webhook': typeof ApiPixWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/conquistas': typeof ConquistasRoute
  '/mais-caem': typeof MaisCaemRoute
  '/placas': typeof PlacasRoute
  '/psicotecnico': typeof PsicotecnicoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulado': typeof SimuladoRoute
  '/simulado-demo': typeof SimuladoDemoRoute
  '/turbo': typeof TurboRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
  '/api/pix/create': typeof ApiPixCreateRoute
  '/api/pix/status': typeof ApiPixStatusRoute
  '/api/pix/webhook': typeof ApiPixWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/biblioteca'
    | '/cadastro'
    | '/checkout'
    | '/conquistas'
    | '/mais-caem'
    | '/placas'
    | '/psicotecnico'
    | '/reset-password'
    | '/simulado'
    | '/simulado-demo'
    | '/turbo'
    | '/biblioteca/$id'
    | '/api/pix/create'
    | '/api/pix/status'
    | '/api/pix/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/biblioteca'
    | '/cadastro'
    | '/checkout'
    | '/conquistas'
    | '/mais-caem'
    | '/placas'
    | '/psicotecnico'
    | '/reset-password'
    | '/simulado'
    | '/simulado-demo'
    | '/turbo'
    | '/biblioteca/$id'
    | '/api/pix/create'
    | '/api/pix/status'
    | '/api/pix/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/biblioteca'
    | '/cadastro'
    | '/checkout'
    | '/conquistas'
    | '/mais-caem'
    | '/placas'
    | '/psicotecnico'
    | '/reset-password'
    | '/simulado'
    | '/simulado-demo'
    | '/turbo'
    | '/biblioteca/$id'
    | '/api/pix/create'
    | '/api/pix/status'
    | '/api/pix/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  ConquistasRoute: typeof ConquistasRoute
  MaisCaemRoute: typeof MaisCaemRoute
  PlacasRoute: typeof PlacasRoute
  PsicotecnicoRoute: typeof PsicotecnicoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimuladoRoute: typeof SimuladoRoute
  SimuladoDemoRoute: typeof SimuladoDemoRoute
  TurboRoute: typeof TurboRoute
  ApiPixCreateRoute: typeof ApiPixCreateRoute
  ApiPixStatusRoute: typeof ApiPixStatusRoute
  ApiPixWebhookRoute: typeof ApiPixWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais-caem': {
      id: '/mais-caem'
      path: '/mais-caem'
      fullPath: '/mais-caem'
      preLoaderRoute: typeof MaisCaemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placas': {
      id: '/placas'
      path: '/placas'
      fullPath: '/placas'
      preLoaderRoute: typeof PlacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicotecnico': {
      id: '/psicotecnico'
      path: '/psicotecnico'
      fullPath: '/psicotecnico'
      preLoaderRoute: typeof PsicotecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado': {
      id: '/simulado'
      path: '/simulado'
      fullPath: '/simulado'
      preLoaderRoute: typeof SimuladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado-demo': {
      id: '/simulado-demo'
      path: '/simulado-demo'
      fullPath: '/simulado-demo'
      preLoaderRoute: typeof SimuladoDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turbo': {
      id: '/turbo'
      path: '/turbo'
      fullPath: '/turbo'
      preLoaderRoute: typeof TurboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$id': {
      id: '/biblioteca/$id'
      path: '/$id'
      fullPath: '/biblioteca/$id'
      preLoaderRoute: typeof BibliotecaIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/api/pix/create': {
      id: '/api/pix/create'
      path: '/api/pix/create'
      fullPath: '/api/pix/create'
      preLoaderRoute: typeof ApiPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pix/status': {
      id: '/api/pix/status'
      path: '/api/pix/status'
      fullPath: '/api/pix/status'
      preLoaderRoute: typeof ApiPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pix/webhook': {
      id: '/api/pix/webhook'
      path: '/api/pix/webhook'
      fullPath: '/api/pix/webhook'
      preLoaderRoute: typeof ApiPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaIdRoute: typeof BibliotecaIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaIdRoute: BibliotecaIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  ConquistasRoute: ConquistasRoute,
  MaisCaemRoute: MaisCaemRoute,
  PlacasRoute: PlacasRoute,
  PsicotecnicoRoute: PsicotecnicoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimuladoRoute: SimuladoRoute,
  SimuladoDemoRoute: SimuladoDemoRoute,
  TurboRoute: TurboRoute,
  ApiPixCreateRoute: ApiPixCreateRoute,
  ApiPixStatusRoute: ApiPixStatusRoute,
  ApiPixWebhookRoute: ApiPixWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
